### ISSUE TITLE
Contenta cms with gatsby

### ISSUE THREAD

**Issue by Prabuela** [contentacms/contenta_gatsby#2]
success open and validate gatsby-configs - 0.066 s
success load plugins - 2.036 s
success onPreInit - 0.058 s
success initialize cache - 0.064 s
success copy gatsby files - 0.263 s
success onPreBootstrap - 0.070 s
Starting to fetch data from Drupal
error fetching articles Error: Request failed with status code 404
    at createError (/var/www/html/gatsby_demo/node_modules/gatsby-source-contenta/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/www/html/gatsby_demo/node_modules/gatsby-source-contenta/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/var/www/html/gatsby_demo/node_modules/gatsby-source-contenta/node_modules/axios/lib/adapters/http.js:191:11)
    at IncomingMessage.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    adapter: [Function: httpAdapter],
    transformRequest: { '0': [Function: transformRequest] },
    transformResponse: { '0': [Function: transformResponse] },
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.16.2'
    },
    method: 'get',
    url: 'http://localhost/myproject/api/recipes',
    data: undefined
  },
........

**Comment by Prabuela** [comment]
request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'GET /myproject/api/recipes HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.16.2\r\n' +
        'Host: localhost\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      path: '/myproject/api/recipes',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Writable],
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n' +
      '<html><head>\n' +
      '<title>404 Not Found</title>\n' +
      '</head><body>\n' +
      '<h1>Not Found</h1>\n' +
      '<p>The requested URL was not found on this server.</p>\n' +
      '<hr>\n' +
      '<address>Apache/2.4.18 (Ubuntu) Server at localhost Port 80</address>\n' +
      '</body></html>\n'
  }
}

 ERROR #11321  PLUGIN

"gatsby-source-contenta" threw an error while running the sourceNodes lifecycle:

Cannot read property 'data' of undefined



  TypeError: Cannot read property 'data' of undefined
  
  - gatsby-node.js:50 Object.exports.sourceNodes
    [gatsby_demo]/[gatsby-source-contenta]/gatsby-node.js:50:42
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  

warn The gatsby-source-contenta plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 0.349 s
success Add explicit types - 0.046 s
success Add inferred types - 0.467 s
success Processing types - 0.247 s
success building schema - 0.918 s
success createPages - 0.031 s
success createPagesStatefully - 0.177 s
success onPreExtractQueries - 0.054 s
success update schema - 0.103 s
success extract queries from components - 0.693 s
success write out requires - 0.116 s
success write out redirect data - 0.052 s
success Build manifest and related icons - 0.379 s
success onPostBootstrap - 0.438 s
⠀
info bootstrap finished - 12.208 s
⠀
success run static queries - 0.111 s — 3/3 44.03 queries/second
success run page queries - 0.067 s — 5/5 168.10 queries/second
success start webpack server - 2.447 s — 1/1 3.31 pages/second
 DONE  Compiled successfully in 8248ms                                                                              4:40:13 PM
⠀
You can now view gatsby-starter-default in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
info ℹ ｢wdm｣: Compiled successfully.

**Comment by Prabuela** [comment]
My config.js
==========
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-source-contenta`,
      options: {
        baseUrl: `http://localhost/myproject`,
      },
    },
    `gatsby-plugin-offline`
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}

**Comment by Prabuela** [comment]
Base url path is incorrect
